#!/usr/bin/env node

var marked = require('marked');
var yaml = require('js-yaml');
var async = require('async');
var path = require('path');

marked.setOptions({
  renderer: new marked.Renderer(),
  gfm: true,
  tables: true,
  breaks: false,
  pedantic: false,
  sanitize: false,
  smartLists: true,
  smartypants: false
});


var fs = require('fs');
var path = require('path');
var files = fs.readdirSync(__dirname + '/rules').map(function (file) {
  return path.join(__dirname, '/rules', file);
});

async.map(files, function (file, callback) {

  fs.readFile(file, 'utf8', function (err, content) {
    if (err) return callback(err);
    var meta = {};

    if (content.split('\n')[0] === '---') {
      var split = content.split('---');
      meta = yaml.safeLoad(split[1]);
      content = split.slice(2).join('---');
    }

    if (!meta.gallery) {
      return callback();
    }

    var lex = marked.lexer(content);

    var title = lex.filter(function (t) {
      return t.type === 'heading';
    })[0].text;

    var descriptionMD = lex.filter(function (t) {
      return !~['heading', 'code'].indexOf(t.type);
    });
    descriptionMD.links = {};
    var description = marked.parser(descriptionMD);

    var code = lex.filter(function (t) {
      return t.type === 'code';
    })[0].text;

    var result = {
      id:          path.basename(file).replace('.md', ''),
      title:       title || meta.title,
      categories:  meta.categories || ['default'],
      description: description,
      code:        code,
    };

    callback(null, result);
  });
}, function (err, results) {
  if (err) {
    console.log(err.stack);
    process.exit(1);
  }

  //group by category
  var rules = results;

  var categories = rules.filter(function (rt) {
    return !!rt;
  }).map(function (rule) {
    return rule.categories;
  }).reduce(function (prev, curr) {
    var new_cats = curr.filter(function (cat) {
      return !~prev.indexOf(cat);
    });
    return prev.concat(new_cats);
  }, []).map(function (cat) {
    return {
      name:      cat,
      templates: rules.filter(function (t) {
        return t && ~t.categories.indexOf(cat);
      })
    };
  });

  console.log('all good!');
  fs.writeFileSync(__dirname + '/rules.json', JSON.stringify(categories, null, 2));
  process.exit(0);
});
